# version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tailscale_mgr
    ports: ["5433:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]
  api:
    build: server
    ports: ["8000:8000"]
    env_file: server/.env
    depends_on: [db]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  
  web:
    build: web-admin
    ports: ["3000:3000"]
    environment:
      - VITE_API=http://localhost:8000
    depends_on: [api]
    command: npm run dev -- --host 0.0.0.0 --port 3000

volumes:
  dbdata:
