#!/bin/bash
# Quick fix script generated by verification

echo "🔧 Running quick fixes..."

# Fix Redis memory
if ! grep -q "vm.overcommit_memory = 1" /etc/sysctl.conf 2>/dev/null; then
    echo "Fixing Redis memory overcommit..."
    echo 'vm.overcommit_memory = 1' | sudo tee -a /etc/sysctl.conf
    sudo sysctl vm.overcommit_memory=1
fi

# Add missing .env variables
if ! grep -q "REDIS_HOST=" .env; then
    echo "Adding Redis configuration to .env..."
    echo "" >> .env
    echo "# Redis Configuration" >> .env
    echo "REDIS_HOST=redis" >> .env
    echo "REDIS_PORT=6379" >> .env
    echo "REDIS_DB=0" >> .env
fi

# Rebuild and restart
echo "Rebuilding containers..."
docker-compose down
docker-compose build --no-cache
docker-compose up -d

echo "✅ Quick fixes applied. Check status with: docker-compose ps"
